workflows:
  # Android Build Workflow
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.bloomee.tunes"
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter test
        script: flutter test
      - name: Build APK
        script: flutter build apk --release
      - name: Build App Bundle
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true

  # Web Build Workflow (Optional)
  web-workflow:
    name: Web Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter test
        script: flutter test
      - name: Build Web
        script: flutter build web --release
    artifacts:
      - build/web/**/*
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true