workflows:
  # Android Build Workflow
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.bloomee.tunes"
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter test
        script: flutter test
      - name: Build APK
        script: flutter build apk --release
      - name: Build App Bundle
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true

  # iOS Build Workflow
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      groups:
        - app_store_connect
      vars:
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...)
        CERTIFICATE_PRIVATE_KEY: Encrypted(...)
    scripts:
      - name: Set up keychain to be used for codesigning
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $APP_STORE_CONNECT_ISSUER_ID $APP_STORE_CONNECT_KEY_IDENTIFIER $APP_STORE_CONNECT_PRIVATE_KEY --type IOS_APP_STORE --create
      - name: Set up signing certificate
        script: |
          keychain add-certificates
      - name: Set up provisioning profile
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter test
        script: flutter test
      - name: Build iOS
        script: flutter build ios --release --no-codesign
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/Runner.xcworkspace" \
            --scheme Runner \
            --archive-flags="-allowProvisioningUpdates"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: api_key
        submit_to_testflight: true
        beta_groups:
          - group name 1
          - group name 2
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true

  # Web Build Workflow
  web-workflow:
    name: Web Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter test
        script: flutter test
      - name: Build Web
        script: flutter build web --release
    artifacts:
      - build/web/**/*
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true

  # Desktop Build Workflow (macOS)
  macos-workflow:
    name: macOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter test
        script: flutter test
      - name: Build macOS
        script: flutter build macos --release
    artifacts:
      - build/macos/Build/Products/Release/*.app
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true

  # Desktop Build Workflow (Windows)
  windows-workflow:
    name: Windows Build
    max_build_duration: 120
    instance_type: windows_x2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter test
        script: flutter test
      - name: Build Windows
        script: flutter build windows --release
    artifacts:
      - build/windows/runner/Release/*.exe
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true

  # Desktop Build Workflow (Linux)
  linux-workflow:
    name: Linux Build
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter test
        script: flutter test
      - name: Build Linux
        script: flutter build linux --release
    artifacts:
      - build/linux/x64/release/bundle/*
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true
